name: sdm439 kernel 
on:
  watch:
    types: [started]
    
env: 
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@master
      
       - name: Start Building
         run: |
            bash ./build.sh
            
       - name: File transferred out of the
         run: |
            cd $GITHUB_WORKSPACE/paper-xm-msm8998-kernel/out/arch/arm64/boot
            curl -sL https://git.io/file-transfer | sh
            zip -q -r kernel.zip *
            ./transfer gof ./kernel.zip
