name: sdm439 kernel 
on:
  watch:
    types: [started]
    
env: 
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@master
      
       - name: Start Building
         run: |
            bash ./build.sh
            
       - name: Build Kernel
         run: |
            bash ./Start.sh
            
       - name: Upload Kernel
         run: |
            bash ./Upload
