name: sdm439 kernel 
on:
  watch:
    types: [started]
    
env: 
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@master
      
       - name: Start Building
         run: |
            chmod +x build.sh && ./build.sh
            
       - name: File transferred out of the
         run: |
            curl -sL https://git.io/cowtransfer | sh
            cd $GITHUB_WORKSPACE/kernel_cherry_sdm439/out/arch/arm64/boot
            zip -q -r kernel.zip *
            ./cowtransfer-uploader ./kernel.zip
