name: sdm439 kernel 
on:
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@master
      
       - name: Start Building
         run: |
            chmod +x build.sh && ./build.sh
